# source (maria db 만 가능)
# source, target (서로 같을 수 없음)
demo:
  datasource:
    source:
      url: jdbc:mariadb://192.168.137.73:3306/pmsportal
      username: lemonbada
      password: fpahsqkek
      driver-class-name: org.mariadb.jdbc.Driver
    target:
      url: jdbc:mariadb://192.168.137.73:3306/pmsdata
      username: lemonbada
      password: fpahsqkek
      driver-class-name: org.mariadb.jdbc.Driver
  batch-count: 1000_000
  truncate-target: true
  tables: a_test
  source-schema: pmsportal
  source-where-clause:
  target-schema: pmsdata

logging:
  file:
    path: batch-log
    max-size: 100MB
    max-history: 10
  level:
    root: error
    com.example.demo: debug